/**
 * PocketBase Seed Data
 * 
 * Example data to populate collections in PocketBase.
 * Use the PocketBase Admin Panel to import or create records manually.
 * 
 * Note: IDs are auto-generated by PocketBase, so you don't need to set them.
 */

// ============================================================
// LEADERSHIP DATA
// ============================================================

export const leadershipSeedData = [
  {
    name: "Sarah Johnson",
    role: "Chief Executive Officer",
    bio: "Former VP of Financial Services with 15+ years in fintech innovation.",
    email: "sarah@finwage.com",
    order: 1,
    featured: true,
    social_links: {
      linkedin: "https://linkedin.com/in/sarahjohnson",
      twitter: "https://twitter.com/sarahjohnson"
    }
  },
  {
    name: "Michael Chen",
    role: "Chief Technology Officer",
    bio: "Tech innovator with expertise in blockchain and distributed systems.",
    email: "michael@finwage.com",
    order: 2,
    featured: true,
    social_links: {
      linkedin: "https://linkedin.com/in/michaelchen",
      github: "https://github.com/michaelchen"
    }
  },
  {
    name: "Emily Rodriguez",
    role: "Chief Financial Officer",
    bio: "CPA with 12 years of experience in corporate finance and strategy.",
    email: "emily@finwage.com",
    order: 3,
    featured: true,
    social_links: {
      linkedin: "https://linkedin.com/in/emilyrodriguez"
    }
  },
  {
    name: "James Williams",
    role: "VP of Operations",
    bio: "Operations expert focused on scaling and efficiency.",
    email: "james@finwage.com",
    order: 4,
    featured: false,
    social_links: {
      linkedin: "https://linkedin.com/in/jameswilliams"
    }
  }
];

// ============================================================
// COMPANY VALUES DATA
// ============================================================

export const companyValuesSeedData = [
  {
    title: "Financial Empowerment",
    description: "We believe everyone deserves access to their earned wages, enabling better financial decisions and stability.",
    icon: "Wallet",
    order: 1,
    featured: true
  },
  {
    title: "Transparency",
    description: "Complete visibility into earnings, deductions, and transactions. No hidden fees or surprises.",
    icon: "Eye",
    order: 2,
    featured: true
  },
  {
    title: "Security First",
    description: "Enterprise-grade security to protect employee financial data and payment information.",
    icon: "Shield",
    order: 3,
    featured: true
  },
  {
    title: "Worker-Centric",
    description: "Every feature is designed with worker needs at the forefront, not corporate profits.",
    icon: "Users",
    order: 4,
    featured: true
  },
  {
    title: "Innovation",
    description: "Continuously evolving our platform with cutting-edge technology and features.",
    icon: "Zap",
    order: 5,
    featured: false
  }
];

// ============================================================
// MILESTONES DATA
// ============================================================

export const milestonesSeedData = [
  {
    year: 2020,
    event: "Company Founded",
    description: "FinWage is founded with a mission to revolutionize earned wage access.",
    order: 1,
    featured: true
  },
  {
    year: 2021,
    event: "First 100,000 Users",
    description: "Reached 100,000 active users across 50+ states.",
    order: 2,
    featured: true
  },
  {
    year: 2022,
    event: "Series A Funding",
    description: "Raised $25M in Series A funding to accelerate growth and innovation.",
    order: 3,
    featured: true
  },
  {
    year: 2023,
    event: "1 Million Users Milestone",
    description: "Surpassed 1 million active users with $5B in transactions facilitated.",
    order: 4,
    featured: true
  },
  {
    year: 2024,
    event: "Enterprise Expansion",
    description: "Launched enterprise solutions serving Fortune 500 companies.",
    order: 5,
    featured: true
  }
];

// ============================================================
// JOB POSITIONS DATA
// ============================================================

export const jobPositionsSeedData = [
  {
    title: "Senior Full Stack Engineer",
    department: "Engineering",
    location: "San Francisco, CA",
    type: "Full-time",
    description: "Join our engineering team to build scalable financial systems. You'll work with React, Node.js, and PostgreSQL.",
    requirements: "5+ years experience, BS in CS or equivalent, strong React and Node.js skills",
    salary_range: "$150,000 - $200,000",
    featured: true,
    status: "open"
  },
  {
    title: "Product Manager",
    department: "Product",
    location: "Remote",
    type: "Full-time",
    description: "Lead product strategy for our mobile app and platform features.",
    requirements: "3+ years PM experience, fintech background preferred",
    salary_range: "$130,000 - $170,000",
    featured: true,
    status: "open"
  },
  {
    title: "Data Analyst",
    department: "Analytics",
    location: "Austin, TX",
    type: "Full-time",
    description: "Analyze financial transaction data to drive business insights.",
    requirements: "2+ years data analytics experience, SQL proficiency, Python knowledge",
    salary_range: "$90,000 - $130,000",
    featured: false,
    status: "open"
  },
  {
    title: "Customer Success Manager",
    department: "Sales",
    location: "New York, NY",
    type: "Full-time",
    description: "Be the voice of our enterprise customers and drive their success.",
    requirements: "3+ years B2B SaaS experience, excellent communication skills",
    salary_range: "$80,000 - $120,000",
    featured: true,
    status: "open"
  },
  {
    title: "Security Engineer",
    department: "Engineering",
    location: "San Francisco, CA",
    type: "Full-time",
    description: "Build and maintain security infrastructure for our financial platform.",
    requirements: "5+ years cybersecurity experience, compliance knowledge (SOC2, PCI-DSS)",
    salary_range: "$160,000 - $210,000",
    featured: false,
    status: "open"
  }
];

// ============================================================
// BENEFITS DATA
// ============================================================

export const benefitsSeedData = [
  {
    title: "Competitive Salary",
    description: "Market-leading compensation packages with annual review increases.",
    icon: "DollarSign",
    category: "Compensation",
    order: 1
  },
  {
    title: "Health Insurance",
    description: "Comprehensive medical, dental, and vision coverage for you and your family.",
    icon: "Heart",
    category: "Health",
    order: 2
  },
  {
    title: "401(k) Matching",
    description: "We match 100% of contributions up to 6% of your salary.",
    icon: "TrendingUp",
    category: "Retirement",
    order: 3
  },
  {
    title: "Unlimited PTO",
    description: "Flexible time off policy because we trust our team to manage their time.",
    icon: "Calendar",
    category: "Time Off",
    order: 4
  },
  {
    title: "Remote Work",
    description: "Work from anywhere with flexible work-from-home arrangements.",
    icon: "Laptop",
    category: "Flexibility",
    order: 5
  },
  {
    title: "Professional Development",
    description: "$2,000 annual budget for courses, conferences, and training.",
    icon: "BookOpen",
    category: "Learning",
    order: 6
  },
  {
    title: "Stock Options",
    description: "Share in company success with equity grants for all employees.",
    icon: "Zap",
    category: "Equity",
    order: 7
  },
  {
    title: "Mental Health Support",
    description: "Free access to mental health counseling and wellness programs.",
    icon: "Smile",
    category: "Wellness",
    order: 8
  }
];

// ============================================================
// COMPANY STATS DATA
// ============================================================

export const companyStatsSeedData = [
  {
    metric: "Active Users",
    value: "2.5M+",
    label: "million workers",
    description: "Employees using FinWage to access earned wages",
    order: 1
  },
  {
    metric: "Total Facilitated",
    value: "$10B+",
    label: "in transactions",
    description: "Cumulative wage advances facilitated since founding",
    order: 2
  },
  {
    metric: "Employer Partners",
    value: "500+",
    label: "companies",
    description: "Organizations offering FinWage to their employees",
    order: 3
  },
  {
    metric: "States Covered",
    value: "50",
    label: "plus DC",
    description: "Available throughout the United States",
    order: 4
  },
  {
    metric: "Uptime",
    value: "99.99%",
    label: "guaranteed",
    description: "Industry-leading platform availability",
    order: 5
  }
];

// ============================================================
// FAQ CATEGORIES DATA
// ============================================================

export const faqCategoriesSeedData = [
  {
    name: "Getting Started",
    description: "Learn how to get started with FinWage",
    order: 1
  },
  {
    name: "How It Works",
    description: "Understand how earned wage access works",
    order: 2
  },
  {
    name: "Security & Privacy",
    description: "Your data security and privacy questions",
    order: 3
  },
  {
    name: "Pricing & Fees",
    description: "Questions about pricing and fees",
    order: 4
  },
  {
    name: "Employer Solutions",
    description: "For employers interested in offering FinWage",
    order: 5
  }
];

// ============================================================
// FAQ ITEMS DATA
// ============================================================

export const faqItemsSeedData = [
  {
    question: "What is earned wage access?",
    answer: "Earned wage access (EWA) allows employees to access a portion of their wages as they earn them, rather than waiting for their regular payday. It's a voluntary benefit that helps workers manage unexpected expenses without turning to payday loans or credit cards.",
    category: "How It Works", // Link to category
    order: 1,
    featured: true
  },
  {
    question: "Is FinWage safe and secure?",
    answer: "Yes, FinWage uses enterprise-grade encryption and security protocols. We're compliant with SOC 2 Type II, PCI-DSS, and all major data protection regulations. Your financial information is protected with the same technology used by major banks.",
    category: "Security & Privacy",
    order: 1,
    featured: true
  },
  {
    question: "Are there any fees?",
    answer: "FinWage offers flexible fee options. You can choose a completely free tier with limited features, or opt for our premium service with advanced features. All fees are transparent and shown before you proceed.",
    category: "Pricing & Fees",
    order: 1,
    featured: true
  },
  {
    question: "How quickly can I get my wages?",
    answer: "Most wage advances are processed within 1-2 business hours. In some cases, transfers may appear instantly, but this depends on your bank's processing times.",
    category: "Getting Started",
    order: 2,
    featured: false
  },
  {
    question: "Can my employer see my transactions?",
    answer: "No, your employer cannot see your individual transactions or usage of FinWage. This is purely personal financial information between you and FinWage.",
    category: "Security & Privacy",
    order: 2,
    featured: false
  }
];

// ============================================================
// CONTACT OPTIONS DATA
// ============================================================

export const contactOptionsSeedData = [
  {
    title: "Email Support",
    description: "Reach our support team via email for detailed assistance.",
    icon: "Mail",
    type: "email",
    action_url: "mailto:support@finwage.com",
    featured: true
  },
  {
    title: "Live Chat",
    description: "Get instant answers to your questions during business hours.",
    icon: "MessageCircle",
    type: "chat",
    action_url: "https://finwage.com/chat",
    featured: true
  },
  {
    title: "Phone Support",
    description: "Call our dedicated support line for urgent assistance.",
    icon: "Phone",
    type: "phone",
    action_url: "tel:1-800-FIN-WAGE",
    featured: true
  },
  {
    title: "Contact Form",
    description: "Submit your inquiry through our online form.",
    icon: "FormInput",
    type: "form",
    action_url: "https://finwage.com/contact",
    featured: false
  }
];

// ============================================================
// SUPPORT RESOURCES DATA
// ============================================================

export const supportResourcesSeedData = [
  {
    title: "Getting Started Guide",
    description: "Complete guide to set up and start using FinWage.",
    url: "https://docs.finwage.com/getting-started",
    category: "Guides",
    order: 1
  },
  {
    title: "Security & Privacy Policy",
    description: "Learn about how we protect your data.",
    url: "https://finwage.com/privacy",
    category: "Legal",
    order: 2
  },
  {
    title: "API Documentation",
    description: "Technical documentation for developers integrating FinWage.",
    url: "https://api.finwage.com/docs",
    category: "Developer",
    order: 3
  },
  {
    title: "Blog",
    description: "Financial wellness tips and industry insights.",
    url: "https://finwage.com/blog",
    category: "Resources",
    order: 4
  },
  {
    title: "Community Forum",
    description: "Connect with other FinWage users and get community support.",
    url: "https://community.finwage.com",
    category: "Community",
    order: 5
  }
];

// ============================================================
// OFFICE LOCATIONS DATA
// ============================================================

export const officeLocationsSeedData = [
  {
    name: "San Francisco HQ",
    address: "123 Financial Street",
    city: "San Francisco",
    state: "California",
    zip: "94105",
    country: "United States",
    phone: "+1 (415) 555-0123",
    email: "sf@finwage.com",
    coordinates: {
      lat: 37.7749,
      lon: -122.4194
    }
  },
  {
    name: "New York Office",
    address: "456 Wall Street",
    city: "New York",
    state: "New York",
    zip: "10005",
    country: "United States",
    phone: "+1 (212) 555-0456",
    email: "ny@finwage.com",
    coordinates: {
      lat: 40.7128,
      lon: -74.0060
    }
  },
  {
    name: "Austin Tech Office",
    address: "789 Tech Boulevard",
    city: "Austin",
    state: "Texas",
    zip: "78704",
    country: "United States",
    phone: "+1 (512) 555-0789",
    email: "austin@finwage.com",
    coordinates: {
      lat: 30.2672,
      lon: -97.7431
    }
  }
];

// ============================================================
// CATEGORIES DATA
// ============================================================

export const categoriesSeedData = [
  {
    name: "Financial Wellness",
    slug: "financial-wellness",
    description: "Tips and articles about managing personal finances",
    color: "#3B82F6",
    icon: "Wallet",
    count: 12
  },
  {
    name: "Employer Benefits",
    slug: "employer-benefits",
    description: "Information for employers about FinWage benefits",
    color: "#10B981",
    icon: "Users",
    count: 8
  },
  {
    name: "Industry Trends",
    slug: "industry-trends",
    description: "Latest trends in fintech and wage access",
    color: "#F59E0B",
    icon: "TrendingUp",
    count: 15
  },
  {
    name: "Compliance",
    slug: "compliance",
    description: "Regulatory updates and compliance information",
    color: "#8B5CF6",
    icon: "Shield",
    count: 6
  }
];

// ============================================================
// PRESS RELEASES DATA
// ============================================================

export const pressReleasesSeedData = [
  {
    title: "FinWage Reaches 2.5 Million Users",
    content: "FinWage announced today that it has reached 2.5 million active users, facilitating over $10 billion in wage advances since its founding in 2020...",
    published_date: "2025-01-15",
    source: "PR Newswire",
    url: "https://prnewswire.com/news/finwage-2.5m",
    featured: true,
    published: true
  },
  {
    title: "FinWage Launches Enterprise Solutions",
    content: "FinWage today introduced its enterprise solutions platform for Fortune 500 companies seeking to offer earned wage access to employees...",
    published_date: "2025-01-10",
    source: "Business Wire",
    url: "https://businesswire.com/news/finwage-enterprise",
    featured: true,
    published: true
  },
  {
    title: "FinWage Receives SOC 2 Type II Certification",
    content: "FinWage announced the successful completion of its SOC 2 Type II audit, strengthening security and compliance posture...",
    published_date: "2024-12-20",
    source: "Company News",
    url: "https://finwage.com/news/soc2",
    featured: false,
    published: true
  }
];

// ============================================================
// EXPORT ALL SEED DATA
// ============================================================

export const allSeedData = {
  leadership: leadershipSeedData,
  company_values: companyValuesSeedData,
  milestones: milestonesSeedData,
  job_positions: jobPositionsSeedData,
  benefits: benefitsSeedData,
  company_stats: companyStatsSeedData,
  faq_categories: faqCategoriesSeedData,
  faq_items: faqItemsSeedData,
  contact_options: contactOptionsSeedData,
  support_resources: supportResourcesSeedData,
  office_locations: officeLocationsSeedData,
  categories: categoriesSeedData,
  press_releases: pressReleasesSeedData
};
